"""Apply approved fixes: rewrite package.json, commit, open PR, save history."""
import os
import json
import uuid
import subprocess
from datetime import datetime, timezone
from agent.state import AgentState, Fix
from agent.db import atlas


def apply_node(state: AgentState) -> dict:
    if not state.get("approved"):
        print("[apply] Fixes rejected — nothing applied")
        return {"pr_url": None}

    fixes: list[Fix] = [f for f in state.get("fixes", []) if f["verified"]]
    if not fixes:
        print("[apply] No verified fixes to apply")
        return {"pr_url": None}

    repo_path = state.get("repo_path", ".")
    pkg_json_path = os.path.join(repo_path, "package.json")

    try:
        with open(pkg_json_path) as f:
            pkg = json.load(f)
    except FileNotFoundError:
        print(f"[apply] package.json not found at {pkg_json_path}")
        return {"pr_url": None}

    # apply version bumps
    changed: list[str] = []
    for fix in fixes:
        for section in ("dependencies", "devDependencies", "peerDependencies"):
            if fix["package"] in pkg.get(section, {}):
                old = pkg[section][fix["package"]]
                pkg[section][fix["package"]] = f"^{fix['target_version']}"
                changed.append(f"{fix['package']}: {old} → ^{fix['target_version']}")

    if not changed:
        print("[apply] No matching packages found in package.json sections")
        return {"pr_url": None}

    with open(pkg_json_path, "w") as f:
        json.dump(pkg, f, indent=2)
        f.write("\n")

    print(f"[apply] Updated package.json:")
    for c in changed:
        print(f"  {c}")

    pr_url = _open_pr(repo_path, fixes, changed)
    _record_history(state, fixes, pr_url)

    return {"pr_url": pr_url}


def _open_pr(repo_path: str, fixes: list[Fix], changed: list[str]) -> str | None:
    branch = f"cve-fix-{uuid.uuid4().hex[:8]}"
    cve_list = ", ".join(f["cve_id"] for f in fixes)
    title = f"fix: bump dependencies to address {cve_list}"
    body_lines = ["## Security fixes\n"]
    for fix in fixes:
        body_lines.append(f"- **{fix['package']}**: `{fix['current_version']}` → `{fix['target_version']}`")
        body_lines.append(f"  - {fix['cve_id']}: {fix['reasoning']}")
    body_lines.append("\n_Generated by CVE Auto-Fix Agent_")
    body = "\n".join(body_lines)

    try:
        subprocess.run(["git", "-C", repo_path, "checkout", "-b", branch], check=True, capture_output=True)
        subprocess.run(["git", "-C", repo_path, "add", "package.json"], check=True, capture_output=True)
        subprocess.run(
            ["git", "-C", repo_path, "commit", "-m", title],
            check=True, capture_output=True,
        )
        subprocess.run(["git", "-C", repo_path, "push", "-u", "origin", branch], check=True, capture_output=True)
        result = subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", body],
            capture_output=True, text=True, cwd=repo_path,
        )
        pr_url = result.stdout.strip()
        print(f"[apply] PR opened: {pr_url}")
        return pr_url
    except subprocess.CalledProcessError as e:
        print(f"[apply] Git/PR step failed: {e.stderr.decode() if e.stderr else e}")
        return None
    except FileNotFoundError as e:
        print(f"[apply] Command not found (git/gh): {e}")
        return None


def _record_history(state: AgentState, fixes: list[Fix], pr_url: str | None) -> None:
    run_id = state.get("run_id", str(uuid.uuid4()))
    repo_path = state.get("repo_path", ".")
    repo = _get_repo_name(repo_path)
    now = datetime.now(timezone.utc).isoformat()

    for fix in fixes:
        atlas.save_fix_history({
            "run_id": run_id,
            "repo": repo,
            "cve_id": fix["cve_id"],
            "package": fix["package"],
            "old_version": fix["current_version"],
            "new_version": fix["target_version"],
            "status": "applied" if pr_url else "applied-local",
            "pr_url": pr_url,
            "timestamp": now,
        })
    print(f"[apply] Saved {len(fixes)} fix record(s) to Atlas fix_history")


def _get_repo_name(repo_path: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", repo_path, "remote", "get-url", "origin"],
            capture_output=True, text=True,
        )
        url = result.stdout.strip()
        # extract owner/repo from git URL
        import re
        m = re.search(r"[:/]([^/]+/[^/]+?)(?:\.git)?$", url)
        return m.group(1) if m else repo_path
    except Exception:
        return repo_path
